### ISSUE TITLE
Exponents calculation in positional encoding 

### ISSUE THREAD

**Issue by enhuiz** [ivanvovk/WaveGrad#12]
https://github.com/ivanvovk/WaveGrad/blob/f59d4bd257144183d0db44bc616c4af5fc51dfe6/model/linear_modulation.py#L21-L24

At line 22, the exponents are calculated as: `exponents = exponents ** 1e-4` instead of  `exponents = 1e-4 ** exponents` from the original transformer paper.

This makes the values very closed to each other at different dimensions, I plot an example using `exponents = exponents ** 1e-4
`, with noise level `linspace(0, 1, 250)` and `n_channels=512`.

![Figure_1](https://user-images.githubusercontent.com/12977366/98900458-c4594a80-24ec-11eb-9e43-07aa9a1bbeac.png)
 
After changing to `exponents = 1e-4 ** exponents`, the positional encoding looks fine:

![Figure_2](https://user-images.githubusercontent.com/12977366/98900801-7d1f8980-24ed-11eb-8716-55a0ad77c6a4.png)

The strange thing is that even with the current position coding, the model seems to be trained well. I tried to train on LibriTTS, and the generated speech sounds okay to me. I'll try to switch to the latter and see whether there will be an improvement.

**Comment by ivanvovk** [comment]
@enhuiz thanks for another one feedback. I agree with you that it should be `exponents = 1e-4 ** exponents`! However, I think for model it is still interpretable at some point since we cat `sin` and `cos`, which makes more or less individual (locally) encoding for noise levels at range of [0, 1]. But, obviously, what happens currently, it is not good. Please, report on your experiment with the second approach! I will also try.

**Comment by enhuiz** [comment]
Hi @ivanvovk, I have tried to fix the positional encoding and retrain the model, though the grad_norm get lower, the test result seems much worse (from both the test loss curve and the generated samples).

![image](https://user-images.githubusercontent.com/12977366/99056060-b67ef480-25d4-11eb-936d-f539c14c9e32.png)

I guess there could be some other issues, so I check the other part of the code and find here is a mismatch between the implementation and the paper (formula 11).

https://github.com/ivanvovk/WaveGrad/blob/d230621964fceac1783bfcb265f7140afd29350d/model/diffusion_process.py#L103

An sqrt() seems lost here.  I'll fix it and try again.

**Comment by ivanvovk** [comment]
@enhuiz yeah, I fixed PE and got the same problems. And yeah, you're right, sqrt() is missed here, need to fix it also.

**Comment by ivanvovk** [comment]
@enhuiz seems like for me sqrt() update solves the problem and now test samples look good.

**Comment by enhuiz** [comment]
![image](https://user-images.githubusercontent.com/12977366/99139877-8f2d3380-2677-11eb-9ae9-c0789a4ff5b6.png)


The loss curve looks better than the previous one, l1_spec_test_batch_loss and total loss are lower, l1_test_batch_loss is higher which is acceptable as it is measure on the audio wave. Training grad and total loss are both lower.

I think I'm still in the early stage. I use niters=1000 to train and niters=50 to test, the audio quality of the fixed version seems not significantly better than the previous one.

[samples-at-12k.zip](https://github.com/ivanvovk/WaveGrad/files/5540212/samples-at-12k.zip)

**Comment by enhuiz** [comment]
https://github.com/ivanvovk/WaveGrad/blob/d230621964fceac1783bfcb265f7140afd29350d/model/diffusion_process.py#L116

I find changing this t to t+1 helps remove the noise in the generated sample after fix pe and sqrt, you may check the following samples:

[samples-at-12k.zip](https://github.com/ivanvovk/WaveGrad/files/5540261/samples-at-12k.zip)

I guess here we need the current sqrt cumprod instead of the previous one.

**Comment by ivanvovk** [comment]
@enhuiz yes, I agree! For me this change improved the quality even more! Somehow missed it when made the implementation... Thanks for revealing all these bugs, man, I really appreciate it. Now it seems to work fine.

**Comment by enhuiz** [comment]
@ivanvovk Good to know it, you are welcome!

**Comment by ivanvovk** [comment]
Closing issue since it is solved.
