### ISSUE TITLE
Were your `generated_samples` generated using a model trained with AMP?

### ISSUE THREAD

**Issue by Hiroshiba** [ivanvovk/WaveGrad#13]
I'm also adding WaveGrad to my implementation. I have a question for you.
Were your `generated_samples` generated using a model trained with AMP?

I think this repository is very nice. Good job!

**Comment by ivanvovk** [comment]
@Hiroshiba yes, the samples are obtained using the model trained with AMP, which checkpoint I have uploaded for the public usage.

**Comment by Hiroshiba** [comment]
I see. Thank you!
