### ISSUE TITLE
predict_start_from_noise

### ISSUE THREAD

**Issue by Liujingxiu23** [ivanvovk/WaveGrad#14]
I do not understand this funcition in the script "diffusion_process.py". Could someone help me?

Frankly speaking，I do not fully understand the process of diffusion and the inverse process.
But for other functions, I can find corresponding equation in the paper "wavegrad" or "Denoising Diffusion Probabilistic Models". But for this function, I cannot.

And the inverse process that generate a wave seems much differ and complex than the process in 
https://github.com/lmnt-com/wavegrad/blob/master/src/wavegrad/inference.py. lines 56~64.
Why is there such a difference？

**Comment by enhuiz** [comment]
Hi @Liujingxiu23 , the code seems to first calculate y_0:

https://github.com/ivanvovk/WaveGrad/blob/d230621964fceac1783bfcb265f7140afd29350d/model/diffusion_process.py#L118

and based on y_0, it calculates the mean and variance of q(y_{t-1} | y_t, y_0).

https://github.com/ivanvovk/WaveGrad/blob/d230621964fceac1783bfcb265f7140afd29350d/model/diffusion_process.py#L123

You can try to do the derivation, except for the clip_denoised, it should be identical to

https://github.com/lmnt-com/wavegrad/blob/master/src/wavegrad/inference.py. lines 56~64.

**Comment by ivanvovk** [comment]
The answer on your question has been given. If you have another questions, feel free to reopen issue or open another one.
