### ISSUE TITLE
On CPU performance

### ISSUE THREAD

**Issue by erogol** [ivanvovk/WaveGrad#2]
Hi thanks for your work and all the info in you README! 

Did you measure the RTF on a CPU?

**Comment by ivanvovk** [comment]
Hi! I'm preparing it. Check it out in a few hours.

**Comment by ivanvovk** [comment]
I have updated RTF info in README. Surprisingly, but my 6-iteration model is a bit slower than the one reported in the paper. Perhaps I have an older model of CPU than authors used for their experiments. **Note: you can always run RTF estimation for your own runtime environment on your own data or just random inputs using the code provided in `notebooks/inference.ipynb` notebook or in `benchmark.py`**.
