### ISSUE TITLE
reduce noise with lower iteration

### ISSUE THREAD

**Issue by taalua** [ivanvovk/WaveGrad#6]
what's your suggestion to reduce the background noise with lower iteration (e.g., 100 iterations) during inference? 
the model is actually okay for inference with 1000 iterations.

**Comment by ivanvovk** [comment]
Which scale are you using for 100 and lower iteration inference? Just a linear one?
For 100 for me it worked to slightly move the left border of linear range. For example, try linspace(1e-5, 1e-2) or linspace(1e-4, 1e-2).

**Comment by ivanvovk** [comment]
I am preparing a huge repo update right now. I will provide schedules for all iterations in it. Stay tuned.

**Comment by ivanvovk** [comment]
@taalua Hello. Sorry for being a bit late, but I have updated the repo and provided lower-iteration schedules! Check it out!
