### ISSUE TITLE
Unable to load the pre-trained parameters for inference

### ISSUE THREAD

**Issue by rahulbhalley** [ivanvovk/WaveGrad#7]
Hey, the quality of generated results is amazing! 🤩 But, unfortunately, I have a little problem with inferencing the model.

I downloaded the checkpoint file you provide named `wavegrad_lj_pretrained.pt` (which I renamed to `checkpoint_wavegrad_lj_pretrained.pt`) and moved to the following location in `WaveGrad` directory.
```
├── logs
│   └── default
│       └── checkpoint_wavegrad_lj_pretrained.pt
```
This is because of the regex requirement existing in the following code

https://github.com/ivanvovk/WaveGrad/blob/714cb827dee4b310c249b6165033228a1ff2ced7/utils.py#L19

which is referred from the fifth cell of [inference.ipynb](https://github.com/ivanvovk/WaveGrad/blob/master/notebooks/inference.ipynb) as following:
```python
# model.load_state_dict(torch.load('../logs/default/checkpoint_180630.pt)['model'], strict=False)
model, _, _ = utils.load_latest_checkpoint(config.training_config.logdir, model)
```

When I run this cell I get the following error. 🙁
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-2e2546d6cd38> in <module>
      1 # model.load_state_dict(torch.load('../logs/default/checkpoint_180630.pt)['model'], strict=False)
----> 2 model, _, _ = utils.load_latest_checkpoint(config.training_config.logdir, model)

~/Desktop/WaveGrad/utils.py in load_latest_checkpoint(logdir, model, optimizer)
     25 
     26 def load_latest_checkpoint(logdir, model, optimizer=None):
---> 27     latest_model_path = latest_checkpoint_path(logdir, regex="checkpoint_*.pt")
     28     print(f'Latest checkpoint: {latest_model_path}')
     29     d = torch.load(

~/Desktop/WaveGrad/utils.py in latest_checkpoint_path(dir_path, regex)
     19 def latest_checkpoint_path(dir_path, regex="checkpoint_*.pt"):
     20     f_list = glob.glob(os.path.join(dir_path, regex))
---> 21     f_list.sort(key=lambda f: int("".join(filter(str.isdigit, f))))
     22     x = f_list[-1]
     23     return x

~/Desktop/WaveGrad/utils.py in <lambda>(f)
     19 def latest_checkpoint_path(dir_path, regex="checkpoint_*.pt"):
     20     f_list = glob.glob(os.path.join(dir_path, regex))
---> 21     f_list.sort(key=lambda f: int("".join(filter(str.isdigit, f))))
     22     x = f_list[-1]
     23     return x

ValueError: invalid literal for int() with base 10: ''
```

Can you please tell me how to fix this issue?

**Comment by ivanvovk** [comment]
Hello, @rahulbhalley . Thank you for your feedback. You already have an answer on your question! :) It is hidden in cell code that you provided:

```python
# model.load_state_dict(torch.load('../logs/default/checkpoint_180630.pt)['model'], strict=False)
model, _, _ = utils.load_latest_checkpoint(config.training_config.logdir, model)
```

Use the commented line to load the weights (set the path to the downloaded checkpoint and that's it). The second line searches for the latest checkpoint by iteration ID from training. You don't need it.

**Comment by ivanvovk** [comment]
Closing issue since the solution is provided.
